In [50]:
# Import modules
import sys
import os
import re
import copy
from os import listdir
from os.path import isfile, join, isdir

# Setting paths
notebooks_path = "./notebooks/markdown/exp/"
content_path = "./content/"
filename_in = [f for f in listdir(notebooks_path) if isfile(join(notebooks_path, f))][0]

# Import notebook file
with open(notebooks_path + filename_in, 'r', encoding = 'utf8') as file:
    doc = file.read()
    file.close()

In [51]:
doc

'# Introduktion til Python til Dataanalyse\n\nDenne lektion gennemg√•r hvordan Python anvendes til dataanalyse. Der introduceres is√¶r til data frames i Python biblioteket "pandas".\n\n# {#Kapitel}Data i Python\n\nI dette f√∏rste kapitel tages et kig p√•, hvad data er for en st√∏rrelse, og hvordan et struktureret datas√¶t ser ud i Python. \n\n# {#Afsnit}Data og datas√¶t\n\nI disse Python lektioner gennemg√•s, hvordan Python anvendes til dataanalyse, men hvad er data overhovedet for noget?\n\nSom udgangspunkt arbejder vi med en meget bred forst√•else af data: alle former for information om noget. Grunden til at der i dag er s√• meget snak om data, dataanalyse, maskinl√¶ring osv., er fordi at stadig mere og mere information digitaliseres, hvorfor det kan g√∏res til genstand for analyser.\n\nNavn, alder, uddannelse, indkomst, yndlingsfilm, mest aflyttede sange i 2020, antal gange rejst med bus 2 i Aalborg, k√∏b i supermarkeder, st√∏rrelse p√• bolig, indbo, brug af el, varme og vand osv. Alle disse informationer er data og alt sammen kan indg√• i analyser til at sige noget om en person eller, mere relevant, flere personer med lignende karakteristika.\n\nData som en mere eller mindre tilf√¶ldig str√∏m af tilf√¶ldig information er vanskelig at arbejde med. Data skal p√• en eller anden m√•de v√¶re i system for, at det kan analyseres - det g√¶lder b√•de maskinel/computationel analyse eller menneskelig analyse.\n\nN√•r man taler om et datas√¶t, mener man typisk en eller anden form for afgr√¶nset m√¶ngde data, der m√•ske eller m√•ske ikke er struktureret i en eller anden form.\n\n## Struktureret og ustruktureret data\n\nMan adskiller typisk mellem struktureret og ustruktureret data.\n\n**Struktureret data**\n\n*Struktureret data* er data, der p√• en eller anden m√•de er sat i system. Den klassiske repr√¶sentation af struktureret data er i et tabul√¶rt format, hvor hver r√¶kke indeholder en *observation* og hver kolonne indeholder en *variabel* (eller "feature", som det omtales inden for maskinl√¶ring. En observation kan v√¶re en person, et land, et firma, et tidspunkt, en kommune osv., mens en variabel er en eller anden form for information om observationen.\n\nTabellen herunder er et eksempel p√• struktureret data:\n\n|Navn |Alder |Besk√¶ftigelse |\n|-----|------|--------------|\n|Lars | 34 | Slagter|\n|Gertrud | 62 | R√•dgiver|\n|Henning | 43 | Revisor|\n|Agnes | 38 | T√∏mrer|\n\nStruktureret data er kendeteget ved at v√¶re sat i system s√•dan, at man umiddelbart kan analysere og sp√∏rge data om noget. I ovenst√•ende tabel kan man fx meget hurtigt unders√∏ge, hvor mange der er √¶ldre end 40, hvem der har et fornavn der starter med "H" eller hvem der har besk√¶ftigelse inden for byggeri.\n\n**Ustruktureret data**\n\n*Ustruktureret data* er data, som - kort sagt - ikke er sat i system. Hvis data ikke er struktureret, vil man typisk kalde det ustruktureret data. Tekst, billeder og video er typiske eksempler p√• ustruktureret data, da disse blot er r√• information uden nogen m√•de at adskille en type information fra en anden. Mange moderne dataanalyseteknikker fokuserer p√• ustruktureret data, hvor man enten udvikler teknikker til at skabe overblik over ustruktureret data eller fors√∏ger at give data en form for struktur.\n\nNedenst√•ende er et eksempel p√• ustruktureret data:\n\n```\n["Hvorfor g√•r man ikke i dialog med \u2066@DRC_dk\u2069 i stedet for at opsige kontrakten uden varsel. Er det kun for at f√∏re st√¶rk mand politik? DRC yder en fremragende indsats p√• baggrund af den opgave de har f√•et #dkpol https://jyllands-posten.dk/indland/ECE12248020/tesfaye-forsoeger-sig-med-en-ny-loesning-paa-alle-udlaendingeministres-problem/\xa0‚Ä¶",\n"Alle t√¶ller ‚ù§Ô∏è https://twitter.com/cekicozlem/status/1276034922587832326\xa0‚Ä¶",\n"Det er s√• godt arbejdeüíö https://twitter.com/fannybroholm/status/1275360842847080449\xa0‚Ä¶",\n"Tilfreds med den klima og energiaftale, der er lavet nu. Det er den f√∏rste delaftale om at n√• 70% reduktion i 2030. S√¶rligt glad for at den indeholder principaftale om en CO2 afgiftsreform #dkpol #dkgreen pic.twitter.com/3slrMxLT5B",\n"Godt f√∏rste skridt for den fri natur #dkpol #dkgreen \u2066@alternativet_\u2069 https://www.altinget.dk/miljoe/artikel/wermelin-lander-aftale-om-de-foerste-naturnationalparker\xa0‚Ä¶",\n"Sp√¶ndende udmelding. \u2066@alternativet_\u2069 √∏nsker ogs√• en gr√∏n   Klimaafgift, hvor udgangspunktet er at forureneren betaler #dkgreen #dkpol https://www.altinget.dk/artikel/venstre-og-radikale-laegger-faelles-pres-paa-regeringen-vil-have-ensartet-co2-afgift?SNSubscribed=true&ref=newsletter&refid=fredag-middag-190620&utm_campaign=altingetdk%20Altinget.dk&utm_medium%09=e-mail&utm_source=nyhedsbrev\xa0‚Ä¶",\n"S√• vigtigt at KL tager ansvar for den proces #dkpol #dkgreen https://www.altinget.dk/miljoe/artikel/professor-om-affaldsaftale-kl-og-kommunerne-skal-gribe-chancen-for-at-loese-tingene-selv\xa0‚Ä¶",\n"Hurra - stor dag for Danmarküíöüëèüèºüëèüèº https://twitter.com/alternativet_/status/1273555055476723713\xa0‚Ä¶",\n"Til klimaforhandlinger i Finansministeriet. Vi sidder og diskuterer rammerne - de n√¶ste dage bliver intensive #dkpol #dkgreen @alternativet_ @ Christiansborg Palace  https://www.instagram.com/p/CBi3d0oB9lB/?igshid=ii78cjnx2n72\xa0‚Ä¶",\n"Aftale om mindre affald, mindre forbr√¶nding og mere genbrug - god dag for klimaet og milj√∏et. 1. skridt i en stor milj√∏pakke #dkpol \u2066@alternativet_\u2069 https://www.dr.dk/nyheder/indland/live-regeringen-praesenterer-ny-aftale-om-affald\xa0‚Ä¶"]\n```\n\nI ovenst√•ende kan man stadig overf√∏re ideen om observationer (i dette tilf√¶lde tweets fra danske politikere), men der er ingen variable eller features givet p√• forh√•nd. Der er derfor ingen umiddelbar struktur at g√∏re brug af for at foretage sig analyser.\n\n## Fra data til dataanalyse\n\nUanset om data er struktureret eller ustruktureret, er de n√¶sten aldrig klar til at analysere med det samme. Data skal n√¶sten altid tilpasses den analyse, som man √∏nsker at foretage og de sp√∏rgsm√•l, som man √∏nsker at f√• svar p√• med sin analyse. \n\nFor struktureret data indeb√¶rer dette at f√• identificeret de relevante dele af sine data (er det fx alle observationer, der er relevante?) samt unders√∏ge og rekode variable s√•dan, at de meningsfuldt kan bruges i sin analyse.\n\nFor ustruktureret data indeb√¶rer det p√• en eller anden m√•de at f√• sat system i eller skabt overblik over data.\n\nOfte vil man ogs√• arbejde med data fra flere kilder, hvorfor en del forarbejde ogs√• kan g√• med at f√• data kombineret i et samlet datas√¶t.\n\n---\n## VIDENSCHECK\n\n*Hvilke af nedenst√•ende er eksempler p√• datas√¶t?:*\n\n* Navnet p√• butikschefen i det lokale supermarked\n* Alle v√¶rker af H.C. Andersen\n* En oversigt over medlemmer af DF√òJ med information om navn, f√∏dsels√•r, arbejdssted og uddannelse\n* Filmen "Vampire\'s Kiss" med Nicolas Cage fra 1988\n* Et kontoudtog\n* Alle film med Nicolas Cage\n\n{{%expand "L√∏sning" %}} Distinktionen mellem data og datas√¶t kan v√¶re vanskelig; s√¶rligt n√•r man ogs√• taler om datas√¶t af ustruktureret data.\n\nHer gives et bud p√• hver.\n\n* Navnet p√• butikschefen i det lokale supermarked: *Ikke et datas√¶t, da det blot er en enkelt information (et enkelt datapunkt)*\n\n\n* Alle v√¶rker af H.C. Andersen: *Et ustruktureret datas√¶t. Literatur- og kulturstudier besk√¶ftiger sig meget med indhold af liter√¶re v√¶rker. Med teknikker i dag kan man godt analysere samlinger af tekst.*\n\n\n* En oversigt over medlemmer af DF√òJ med information om navn, f√∏dsels√•r, arbejdssted og uddannelse: *Et "klassisk" struktureret datas√¶t. Observationerne er medlemmerne af DF√òJ og variablene er de forskellige informationer for hvert medlem.*\n\n\n* Filmen "Vampire\'s Kiss" med Nicolas Cage fra 1988: *Ikke et datas√¶t.*\n\n\n* Et kontoudtog: *Diskutabelt. Ofte er en enkelt persons kontoudtog ikke af megen interesse (udover for personen selv og personens bankr√•dgiver). En samling af kontoudtog vil nok v√¶re mere at betragte som et egentlig datas√¶t (et datas√¶t med transaktioner som observationer og bel√∏b, tidspunkt og beskrivelse som variable), men et enkelt datas√¶t kunne ogs√• betragtes som et datas√¶t af transaktioner for den ene person.*\n\n\n* Alle film med Nicolas Cage: *Et ustruktureret datas√¶t. Lig med v√¶rkerne af H.C. Andersen kunne et studie af dette ogs√• v√¶re af interesse. Computationel analyse af disse er noget mere kompliceret, men mulig!*\n\n{{% /expand%}}\n\n# {#Afsnit}Introduktion til pandas\n\nPakken `pandas` (https://pandas.pydata.org/) er et Python bibliotek til datah√•ndtering og dataanalyse. Pandas egner sig s√¶rligt til data i tabeller struktureret i r√¶kker og kolonner. En datatabel kaldes inden for pandas en "DataFrame"; et bestemt Python objekt specifikt til at lagre og bearbejde data i tabeller.\n\nDenne lektion gennemg√•r diverse basale funktioner til at indl√¶se, udforske og h√•ndtere en pandas DataFrame. Se ogs√• den officielle dokumentation for flere guides, introduktioner og beskrivelser til at arbejde med pandas: https://pandas.pydata.org/docs/\n\n## Indl√¶s og inspicer data med pandas\n\n`pandas` pakken indeholder funktioner til at indl√¶se data i forskellige formater; herunder CSV, JSON, Excel, Stata, SAS osv.\n\nI det nedenst√•ende indl√¶ses pandas biblioteket, hvorefter datas√¶ttet "ESS2014DK_subset.csv" indl√¶ses. Biblioteket `numpy` indl√¶ses ogs√•, da det indeholder en r√¶kke brugbare funktioner til at foretage beregninger p√• pandas dataframes:\n\n\n```python\nimport numpy as np\nimport pandas as pd\n\ness2014 = pd.read_csv(\'https://github.com/CALDISS-AAU/workshop_python-data-analysis/raw/master/datasets/ESS2014DK_sub1.csv\')\n```\n\n{{% notice note %}}\nBem√¶rk importkonventionerne for `numpy` og `pandas`. `numpy` importeres typisk som `np` og `pandas` typisk som `pd`.\n{{% /notice%}}\n\n{{% notice info %}}\nDatas√¶ttet, som indl√¶ses her, er et uddrag af datas√¶ttet fra European Social Survey (ESS) 2014. ESS er en europ√¶isk surveyunders√∏gelse, der gentages hvert andet √•r. Surveyet behandler sp√∏rgsm√•l om folks helbred, besk√¶ftigelse, politiske holdninger, tillid osv. I dette uddrag er der kun inkluderet de danske respondenter og et mindre udpluk variable.\n{{% /notice%}}\n\nDatas√¶ttet er nu indl√¶st som et dataframe objekt i Python, som man kan interagere med. \n\nMetoden `.head()` printer de f√∏rste fem r√¶kker af datas√¶ttet:\n\n\n```python\ness2014.head()\n```\n\n\n\n\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>idno</th>\n      <th>ppltrst</th>\n      <th>happy</th>\n      <th>health</th>\n      <th>cgtsday</th>\n      <th>alcfreq</th>\n      <th>height</th>\n      <th>weight</th>\n      <th>gndr</th>\n      <th>yrbrn</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>921490</td>\n      <td>4</td>\n      <td>Extremely happy</td>\n      <td>Very good</td>\n      <td>NaN</td>\n      <td>Never</td>\n      <td>167.0</td>\n      <td>62.0</td>\n      <td>Female</td>\n      <td>1965</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>938348</td>\n      <td>Most people can be trusted</td>\n      <td>7</td>\n      <td>Good</td>\n      <td>NaN</td>\n      <td>Several times a week</td>\n      <td>168.0</td>\n      <td>70.0</td>\n      <td>Female</td>\n      <td>1973</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>939019</td>\n      <td>5</td>\n      <td>8</td>\n      <td>Good</td>\n      <td>3.0</td>\n      <td>Once a week</td>\n      <td>182.0</td>\n      <td>90.0</td>\n      <td>Male</td>\n      <td>1980</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>924985</td>\n      <td>8</td>\n      <td>9</td>\n      <td>Very good</td>\n      <td>NaN</td>\n      <td>Once a week</td>\n      <td>188.0</td>\n      <td>85.0</td>\n      <td>Male</td>\n      <td>1946</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>925410</td>\n      <td>4</td>\n      <td>8</td>\n      <td>Bad</td>\n      <td>NaN</td>\n      <td>Several times a week</td>\n      <td>156.0</td>\n      <td>60.0</td>\n      <td>Female</td>\n      <td>1969</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n\n\n\nDataframes er et tabul√¶rt dataformat. N√•r en fil indl√¶ses som en pandas dataframe, skal filen derfor v√¶re i et format, der kan konverteres til tabelformat (data i r√¶kker og kolonner).\n\nI dette datas√¶t udg√∏r observationerne (r√¶kkerne) enkeltpersoner, som har besvaret sp√∏rgeskemaet. De enkelte kolonner indeholder oplysninger om de enkelte personer. \nAf ovenst√•ende print af de f√∏rste fem r√¶kke kan man fx l√¶se, at personen i r√¶kke 4 (r√¶kkeindeks 3) er en kvinde f√∏dt i 1958, som er 162 cm h√∏j.\n\n{{% notice info %}} Subsettet af ESS 2014 indeholder f√∏lgende kolonner:\n- `idno`: Personens id-numre/respondentn√∏gle\n- `ppltrst`: Personens vurdering p√• en skala fra 0-10 af, hvor meget de stoler p√• andre mennesker\n- `happy`: Personens vurdering p√• en skala fra 0-10 af, hvor glade de f√∏ler sig\n- `health`: Personens vurdering af eget helbred fra "Very bad" til "Very good"\n- `cgtsday`: Antal cigaretter personen ryger om dagen\n- `alcfreq`: Hvor ofte personen drikker alkohol\n- `height`: Personens h√∏jde i centimeter\n- `weight`: Personens v√¶gt i kilo\n- `gndr`: Personens k√∏n (mand/kvinde)\n- `yrbrn`: Personens f√∏dsels√•r\n{{% /notice %}}\n\n{{% notice info %}} **NaN?**\n\nSom det ses af datas√¶ttet fremg√•r v√¶rdien `NaN` flere gange i datas√¶ttet (s√¶rligt under kolonnen `cgtsday`). \n\n`NaN` angiver missingv√¶rdi. En missingv√¶rdi er en ikke-gyldig v√¶rdi; fx hvis en person ikke svarer, informationen ikke har v√¶ret muligt at skaffe eller andet.\n\n{{% /notice %}}\n\n## Series og dataframes\n\nEn dataframe kan siges at best√• af en samling af kolonner. En kolonne i en dataframe kaldes en `series`.\n\nNavnene p√• kolonnerne, som en dataframe indeholder, kan ses af attributen `.columns`:\n\n\n```python\ness2014.columns\n```\n\n\n\n\n    Index([\'idno\', \'ppltrst\', \'happy\', \'health\', \'cgtsday\', \'alcfreq\', \'height\',\n           \'weight\', \'gndr\', \'yrbrn\'],\n          dtype=\'object\')\n\n\n\nHver kolonne ligger som et attribut i dataframen, og kan derfor tilg√•s direkte. Herunder printes `health` kolonnen:\n\n\n```python\nprint(ess2014.health.head())\n```\n\n    0    Very good\n    1         Good\n    2         Good\n    3    Very good\n    4          Bad\n    Name: health, dtype: object\n    \n\nDog vil man typisk refere til enkeltkolonner p√• denne m√•de:\n\n\n```python\nprint(ess2014[\'health\'].head())\n```\n\n    0    Very good\n    1         Good\n    2         Good\n    3    Very good\n    4          Bad\n    Name: health, dtype: object\n    \n\nDer er ikke forskel mellem de to m√•der at g√∏re det p√•, men sidstviste m√•de er mere g√¶ngs og g√∏r kode mere overskuelig.\n\nTypen kan tjekkes med `type()`. Herunder ses det, at hele dataframen er et dataframe objekt, mens den enkelte kolonne (`health`) er et series objekt:\n\n\n```python\nprint(type(ess2014))\nprint(type(ess2014[\'health\']))\n```\n\n    <class \'pandas.core.frame.DataFrame\'>\n    <class \'pandas.core.series.Series\'>\n    \n\n### Pandas series og lister\n\nEn pandas series er p√• mange m√•der sammenlignelig med en Python liste: Det er en r√¶kke v√¶rdier, hvor hvert element har et indeks.\n\nLigesom med lister, kan enkeltelementer af en series tilg√•s ved at refere til deres indeks:\n\n\n```python\nprint(ess2014[\'health\'][122]) #Printer indeks 122\n```\n\n    Very good\n    \n\nLister kan konverteres direkte til pandas series med `pd.Series()`:\n\n\n```python\na_list = [1, 5, 9, 12, 18]\na_series = pd.Series(a_list)\n\nprint(a_list)\nprint(a_series)\n```\n\n    [1, 5, 9, 12, 18]\n    0     1\n    1     5\n    2     9\n    3    12\n    4    18\n    dtype: int64\n    \n\nL√¶g i ovenst√•ende m√¶rke til, at n√•r en series printes, printes elementernes indeks ud ogs√•. Dette er fordi, at man selv kan specificere indeksv√¶rdier i en pandas series:\n\n\n```python\nvalues = ["value1", "value2", "value3", "value4", "value5"]\na_series = pd.Series(a_list, index = values)\n\nprint(a_series)\n```\n\n    value1     1\n    value2     5\n    value3     9\n    value4    12\n    value5    18\n    dtype: int64\n    \n\nGives en serie indeksv√¶rdier, kan enkeltelementer referes til b√•de med deres indeksnummer og indeksv√¶rdi:\n\n\n```python\nprint(a_series[2]) # Printer den 3. v√¶rdi ud fra indeksnummer (indeks 2)\nprint(a_series[\'value3\']) # Printer den 3. v√¶rdi ud fra indeksv√¶rdi ("value3")\n```\n\n    9\n    9\n    \n\n**Operationer p√• serier**\n\nDen store forskel p√• lister og pandas series er, at man kan foretage beregninger direkte p√• serier.\n\nFx kan man ikke multiplicere enkeltv√¶rdierne i en liste direkte (nedenst√•ende printer bare listen 2 gange):\n\n\n```python\na_list * 2\n```\n\n\n\n\n    [1, 5, 9, 12, 18, 1, 5, 9, 12, 18]\n\n\n\nPandas series kan man derimod foretage operationer direkte p√•:\n\n\n```python\na_series * 2\n```\n\n\n\n\n    value1     2\n    value2    10\n    value3    18\n    value4    24\n    value5    36\n    dtype: int64\n\n\n\nDette g√∏r ogs√•, at man kan bruge funktioner fra fx `numpy` til at udregne forskellige m√•l ud fra en series.\n\nHerunder udregnes fx middelv√¶rdi for `a_series`:\n\n\n```python\nimport numpy as np\n\nnp.mean(a_series)\n```\n\n\n\n\n    9.0\n\n\n\n---\n## √òVELSE: Indl√¶s datas√¶t\n\n1. Indl√¶s datas√¶ttet ESS2014DK_sub1 med `pd.read_csv()`. Funktionen kan indl√¶se data direkte fra et link (husk at importere pandas biblioteket).\n\n    - Link til data: https://github.com/CALDISS-AAU/workshop_python-data-analysis/raw/master/datasets/ESS2014DK_sub1.csv\n    \n2. Brug `np.mean()` (`numpy.mean()`) til at udregne middelv√¶rdien af `height` variablen i datas√¶ttet. Hvad er middelv√¶rdien?\n\n\n\n{{%expand "L√∏sning" %}} \n\n\n```python\nimport pandas as pd\nimport numpy as np\n\ness2014 = pd.read_csv(\'https://github.com/CALDISS-AAU/workshop_python-data-analysis/raw/master/datasets/ESS2014DK_sub1.csv\')\n\nprint(np.mean(ess2014[\'height\']))\n```\n\n    174.15887850467288\n    \n\n{{% /expand%}}\n\n---\n\n# {#Afsnit}Variabeltyper\n\nMan adskiller overordnet mellem to typer af variable; s√¶rligt inden for strukuterede datas√¶t: kontinuerlige og kategoriske. \n\n\n## Kontinuerlige variable\n\nKontinuerlige variable kan tage en n√¶rmest uafgr√¶nset m√¶ngde af forskellige numeriske v√¶rdier, hvor man ikke i forvejen kan afgr√¶nse, hvilke v√¶rdier, som variablen kan antage. Indkomst, v√¶gt og alder er eksempler p√• kontinuerlige variable. Selvf√∏lgelig er der v√¶rdier, som disse variable ikke kan tage - fx negative v√¶rdier - men man kan med disse variable ikke vide i forvejen, hvilke v√¶rdier, man vil ende ud med. \n\nI datas√¶ttet ESS2014DK er `weight`, `height` og `yrbrn` eksempler p√• kontinuerlige variable. \n\nTag fx et kig p√• v√¶rdierne i `height`:\n\n\n```python\ness2014[\'height\'].head(10)\n```\n\n\n\n\n    0    167.0\n    1    168.0\n    2    182.0\n    3    188.0\n    4    156.0\n    5    167.0\n    6    169.0\n    7    184.0\n    8    182.0\n    9    172.0\n    Name: height, dtype: float64\n\n\n\nVariablen indeholder personens h√∏jde i cm og kan derfor antale et stort antal forskellige v√¶rdier. Variablen er kontinuerlig, fordi selvom variablen selvf√∏lgelig ikke kan antage alle v√¶rdier (fx -157 eller 1.234), s√• kan det ikke i forvejen afgr√¶nses pr√¶cist, hvilke v√¶rdier der vil ende i datas√¶ttet.\n\n## Kategoriske variable\n\nKategoriske variable kan i mods√¶tning til kontinuerlige kun antage et afgr√¶nset og i forvejen defineret s√¶t af v√¶rdier. \n\nF√∏dselskommune, partitilh√∏r eller hvorvidt man kan lide jazz, er eksempler p√• 

In [52]:
table_regex = re.compile('\n<div>\n<style scoped>.*?</div>\n', re.DOTALL)

In [53]:
tables = re.findall(table_regex, doc)

In [54]:
table_dict = {}
counter = 1

for table in tables:
    table_placeholder = "{[{TABLE " + str(counter) + "}]}"
    table_dict[table_placeholder] = table
    counter += 1

In [55]:
table_dict_rev = {v: k for k, v in table_dict.items()}

In [56]:
for key in table_dict_rev.keys():
    doc = doc.replace(key, table_dict_rev[key])

In [57]:
with open(notebooks_path + '/python-for-data-analysis_tablefix.md', 'w', encoding = "utf8") as outfile:
    outfile.write(doc)
    outfile.close()

In [44]:
html_path = './public/'

In [58]:
folder_names = [f for f in listdir(content_path) if isdir(join(content_path, f))]

for folder in folder_names:
    content_folder = join(html_path, folder) + "/"
    content_subfolders = [f for f in listdir(content_folder) if isdir(join(content_folder, f))]
    for folder in content_subfolders:
        content_subfolder = content_folder + folder + "/"
        file_names = [f for f in listdir(content_subfolder) if isfile(join(content_subfolder, f))]
        for file_name in file_names:
            with open(content_subfolder + file_name, 'r', encoding = 'utf8') as file:
                doc = file.read()
                file.close()
            for key in table_dict.keys():
                doc = doc.replace(key, table_dict[key])
            with open(content_subfolder + file_name, 'w', encoding = 'utf8') as outfile:
                outfile.write(doc)
                outfile.close()